apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: trips-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: awesomecluster.northeurope.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: poi-service          
          servicePort: 80
        path: /api/poi      
      - backend:
          serviceName: user-java-service
          servicePort: 80
        path: /api/user-java
      - backend:
          serviceName: userprofile-service
          servicePort: 80
        path: /api/user
      - backend:
          serviceName: trips
          servicePort: 80
        path: /api/trips
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: trips-ingress
  namespace: web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: awesomecluster.northeurope.cloudapp.azure.com
    http:
      paths:        
      - backend:
          serviceName: tripviewer-service
          servicePort: 80
        path: /