apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: insurance-monitor
  labels:
    release: prom
    app: insurance
spec:
  endpoints:
  - port: metrics
    path: '/metrics'
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: insurance
      release: prom
