apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "awesomeKeyVault"
    objects: |
      array:
        - |
          objectAlias: SQL_SERVER
          objectName: azure-sql-fdqn              
          objectType: secret
          objectVersion: ""
        - |
          objectAlias: SQL_USER
          objectName: azure-sql-user              
          objectType: secret
          objectVersion: ""
        - |
          objectAlias: SQL_PASSWORD
          objectName: azure-sql-pass              
          objectType: secret
          objectVersion: ""
        - |
          objectAlias: SQL_DATABASE
          objectName: azure-sql-database             
          objectType: secret
          objectVersion: ""                                 
    tenantId: "0b9581bf-cf90-45cc-a02b-0dfde2ace20e"