apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  labels:
    app: user-java
spec:
  ports:
    - port: 80
  selector:
    app: user-java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
  labels:
    app: user-java-deployment
    namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
        namespace: api
    spec:
      containers:
      - name: user-java
        image: registrytjp0542.azurecr.io/tripinsights/user_java:1.0
        ports:
        - containerPort: 80        
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"
